SELECT 
    ACCOUNT_ID AS ACCOUNT_CODE  -- TEXT
,   SYMBOL AS SECURITY_CODE -- TEXT
,   DESCRIPTION AS SECURITY_NAME -- TEXT
,   EXCHANGE AS EXCHANGE_CODE -- TEXT
,   REPORT_DATE AS REPORT_DATE -- DATE 
,   QUANTITY AS QUANTITY -- NUMBER
,   COST_BASE AS COST_BASE -- NUMBER
,   POSITION_VALUE AS POSITION_VALUE -- NUMBER 
,   CURRENCY AS CURRENCY_CODE -- TEXT 
FROM {{source("ub_bank","UB_BANK_POSITION")}}

-- SELECT ', ' || COLUMN_NAME || ' as ' || COLUMN_NAME || ' -- ' || DATA_TYPE  as SQL_TEXT
-- FROM PORTFOLIO_TRACKING.INFORMATION_SCHEMA.COLUMNS
--     WHERE TABLE_SCHEMA = 'SOURCE_DATA' AND
--     TABLE_NAME = 'UB_BANK_POSITION'
--     ORDER BY ORDINAL_POSITION


-- SELECT <SQL_TEXT> FROM {{source('source_system','source_table')}} -- in dbt