SELECT 
    ACCOUNT_ID AS ACCOUNT_CODE  -- TEXT
,   SYMBOL AS SECURITY_CODE -- TEXT
,   DESCRIPTION AS SECURITY_NAME -- TEXT
,   EXCHANGE AS EXCHANGE_CODE -- TEXT
,   REPORT_DATE AS REPORT_DATE -- DATE 
,   QUANTITY AS QUANTITY -- NUMBER
,   COST_BASE AS COST_BASE -- NUMBER
,   POSITION_VALUE AS POSITION_VALUE -- NUMBER 
,   CURRENCY AS CURRENCY_CODE -- TEXT 
FROM {{source("ub_bank","UB_BANK_POSITION")}}