{{config(materialized = 'ephermal')}}
WITH
src_data AS
(
    SELECT SECURITY_CODE as SECURITY_CODE -- TEXT
    , SECURITY_NAME as SECURITY_NAME -- TEXT
    , SECTOR as SECTOR_NAME -- TEXT
    , INDUSTRY as INDUSTRY_NAME --TEXT
    , COUNTRY as COUNTRY_CODE --TEXT
    , EXCHANGE as EXCHANGE_CODE --TEXT
    , LOAD_TS AS LOAD_TS  -- TIMESTAMP_UTC
    , 'SEED.UB_BANK_SECURITY_INFO' AS RECORD_SOURCE 
    FROM  {{source('seeds' , 'UB_BANK_SECURITY_INFO')}}
),

hashed as (
    concat_ws('|', SECURITY_CODE) AS SECURITY_HKEY,
    concat_ws('|',SECURITY_CODE,SECTOR_NAME,SECTOR_NAME,INDUSTRY_NAME,COUNTRY_CODE,EXCHANGE_CODE) AS SECURITY_HDIFF , * EXCLUDE LOAD_TS ,
    LOAD_TS AS LOAD_TS_UTC FROM src_data
)
SELECT * FROM hashed;